// Package quote exists solely for storing quotes as constants.
package quote

const SunAlso = `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ante turpis, egestas facilisis elementum auctor, rutrum vitae nisi. Donec placerat nibh arcu, vitae dapibus neque hendrerit ac. Vivamus finibus mauris sed erat malesuada, in cursus magna egestas. Nulla non arcu tristique lectus malesuada efficitur. Nam libero nisi, posuere quis tellus vitae, pellentesque lacinia felis. In vehicula congue felis, id mollis enim tempor vitae. Suspendisse sed rhoncus massa, at gravida ante. Pellentesque commodo diam non purus elementum, nec sodales nibh feugiat. Suspendisse vel nisi eget augue elementum maximus. Maecenas dictum vel magna sed pellentesque. Praesent non nulla elit.

Ut ornare elit imperdiet velit euismod efficitur. In tempus sed augue quis consequat. Praesent porta mi vel commodo porttitor. Aenean suscipit quis mi ut euismod. Duis massa tellus, posuere porttitor quam at, interdum interdum lectus. Aenean a volutpat felis. In finibus odio vitae molestie volutpat. Vivamus felis odio, posuere et pulvinar vel, porta in nunc. Proin est metus, dictum id viverra ac, porttitor nec diam. Nam at sollicitudin augue. Cras eros nisi, vulputate ac euismod ut, rutrum non est. Proin consequat rhoncus malesuada. Nam pulvinar porttitor quam, sed cursus tellus pulvinar nec. Duis lacinia finibus mi a fringilla. Mauris sed dignissim nunc, sit amet porttitor leo.

Nullam malesuada, odio sit amet interdum mattis, odio eros vehicula tellus, eget euismod nisl metus ac tellus. Maecenas porta vel nulla bibendum consectetur. Vestibulum nec diam ipsum. Quisque nec vulputate sapien, nec commodo nibh. Ut semper, ligula sit amet euismod dictum, risus nulla pretium libero, nec consequat enim leo nec odio. Quisque ultrices pretium viverra. Aliquam at erat et erat tincidunt imperdiet. Phasellus cursus enim lectus, non mattis mi blandit in. Suspendisse potenti. In lectus libero, bibendum vel maximus nec, finibus eu nisi. Sed sed dui cursus, finibus mi aliquam, feugiat justo.

Morbi congue risus vitae nibh finibus, non blandit leo elementum. Mauris pretium sit amet quam vel tristique. Donec vitae libero sed nunc mattis lacinia id ac mauris. Integer tempus odio risus. Praesent vehicula nec diam et porttitor. Aenean eu turpis auctor, feugiat velit vel, hendrerit odio. Suspendisse nec dui sed odio interdum accumsan. Aenean tristique at dui ac elementum. Morbi luctus scelerisque purus, non pulvinar tortor sagittis quis. In pulvinar arcu ipsum, eget sollicitudin risus pulvinar nec. Vestibulum pretium euismod velit non vulputate. Sed eget est libero. Pellentesque et laoreet ante, sit amet tincidunt ipsum. Aenean ultrices molestie nisi.

Proin gravida ultricies pretium. Sed rutrum eget orci ac vestibulum. Vivamus mi libero, facilisis vitae pharetra sed, lacinia sed arcu. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse nulla turpis, aliquam nec augue sed, gravida lacinia mi. Nullam ut quam cursus, sagittis mi at, convallis eros. Vestibulum vulputate sit amet quam sit amet egestas. Maecenas id convallis odio, ut suscipit est. Aliquam erat volutpat. Duis pulvinar nibh scelerisque magna venenatis, id fringilla justo rhoncus. Proin ornare erat ultrices velit aliquet, eu pharetra metus pretium.

Cras faucibus mi felis, sit amet congue nunc lobortis in. Donec quis massa at turpis faucibus scelerisque. Quisque vitae augue auctor, vulputate magna quis, placerat massa. In id blandit purus, at luctus est. Nunc fringilla odio vitae mi ornare consequat. Suspendisse vehicula velit id est pellentesque ultrices. Ut vitae mattis mi. Fusce id nunc purus. Donec vitae elementum justo. Sed lacus tortor, feugiat quis pellentesque vel, dignissim in metus. Morbi quis lacus quis diam placerat vehicula. Proin non ultrices odio, quis rhoncus nunc. Nam fringilla semper eros vitae rutrum. Aliquam placerat, ipsum ac lobortis posuere, sem quam semper urna, a pretium ipsum nisi quis mauris. Maecenas in dolor eu leo commodo tincidunt a ac nunc.

Integer urna leo, posuere vitae aliquam at, efficitur non risus. Cras leo justo, rutrum at est ac, euismod posuere ligula. Fusce aliquam nibh at nisl eleifend, at rutrum massa tristique. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Morbi condimentum ipsum eget dolor dapibus vestibulum. Donec imperdiet aliquam euismod. Vivamus vitae commodo nisl, eu porttitor sapien. Donec volutpat elit sit amet neque volutpat, vestibulum tempus neque maximus. Nunc pretium vestibulum sem, vel bibendum diam semper eu. Nulla molestie vel lectus eget placerat. In non dictum diam. Nam quis sodales ante. Nulla vitae sodales est, ut fermentum nisi.

Interdum et malesuada fames ac ante ipsum primis in faucibus. Sed dapibus nunc ac enim iaculis, in tristique sapien ullamcorper. Etiam congue sem eros, eu ultrices felis euismod sit amet. Suspendisse porttitor velit vitae leo auctor, vel tincidunt arcu sollicitudin. Duis efficitur tortor turpis, at posuere nisl malesuada vel. Mauris dapibus justo sed ligula dapibus, laoreet pellentesque libero eleifend. Donec lobortis, erat id ullamcorper fermentum, nisl est ornare dui, in euismod orci lorem a elit. Fusce suscipit placerat euismod. Nulla tempor nibh et turpis convallis, non sodales leo iaculis. Suspendisse tempus tortor quam, a ornare felis efficitur a.

Etiam pharetra nisl quis libero sodales scelerisque. Nam nibh mauris, tincidunt ac arcu sit amet, vehicula aliquet mi. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Mauris tincidunt arcu eu neque lacinia lacinia. Sed egestas nibh eu volutpat lacinia. Cras nec lorem at urna varius finibus. Nunc iaculis hendrerit tellus, tempor varius ex finibus a. Morbi in eros risus. Pellentesque finibus sapien nunc, et facilisis orci mattis eu. Aliquam dapibus, orci sed aliquam efficitur, orci augue finibus odio, sit amet varius lorem est varius erat. Praesent pellentesque commodo luctus. Vivamus vel turpis auctor, congue elit placerat, molestie felis.

Nulla sodales finibus ligula at imperdiet. Sed vel condimentum metus. Integer rhoncus leo quis elementum lobortis. Nunc ipsum nulla, fermentum a ante sed, vehicula commodo justo. Ut eget magna at leo sollicitudin iaculis in a urna. Proin dui diam, sodales ut dolor vitae, tristique scelerisque tellus. Mauris sem nisi, varius sed magna non, pellentesque porttitor velit. Etiam a purus quis magna varius maximus ut pulvinar nunc. Mauris et purus scelerisque augue feugiat suscipit. Nunc interdum, felis at dictum ultrices, purus massa interdum urna, at finibus massa magna vel tellus. Vestibulum id risus velit. Donec elit mauris, fringilla at dapibus quis, aliquet eget ligula. Pellentesque magna nunc, molestie sit amet mi id, vulputate molestie sem. Donec laoreet lectus quis ligula ultricies iaculis. Sed sollicitudin vehicula feugiat.

Nullam tortor justo, sodales id mollis a, eleifend vel justo. Duis consectetur sit amet urna et dapibus. Phasellus arcu orci, tincidunt non est ut, accumsan pellentesque dui. Sed in semper quam. Praesent finibus hendrerit tincidunt. Pellentesque in pretium risus. Nunc eu turpis at quam blandit euismod. Etiam placerat bibendum interdum. Nullam dictum nisl ut semper ultrices. Donec rutrum enim eros, dignissim mattis justo mattis at. Vestibulum bibendum enim lacus, ut congue massa eleifend sit amet. Sed leo est, efficitur non elit quis, imperdiet sollicitudin urna. Proin accumsan urna et ligula semper, quis lacinia libero ullamcorper. Sed mollis erat eget ex fringilla pretium. Nam lorem justo, tempus quis gravida non, tristique ut sem.

Integer pellentesque metus ac tincidunt laoreet. Mauris semper egestas urna a gravida. Aliquam tristique urna in odio bibendum mollis. Curabitur cursus ex vel condimentum consectetur. In consequat nunc non risus consequat molestie. Donec at magna vitae urna luctus suscipit. Praesent a enim eget mauris elementum tristique. Nullam commodo enim vitae lobortis pulvinar. Donec fringilla tortor augue, vel viverra magna auctor in. Nam faucibus magna in augue porttitor, quis tincidunt nisi suscipit. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Suspendisse eu libero purus. Ut at lobortis sapien. Ut porta erat eu vehicula porta. Donec vestibulum quis orci non aliquet. Duis finibus eget tortor quis pharetra.

Duis laoreet consectetur turpis, eu dictum lacus gravida vitae. Curabitur malesuada odio velit, aliquam facilisis velit congue eget. Praesent imperdiet, nisi et porttitor semper, mauris ligula placerat elit, in pulvinar felis lorem sit amet eros. Quisque tempus dui vitae dui sagittis imperdiet. Morbi a eros aliquam, imperdiet libero ac, ultricies erat. Praesent dignissim egestas ligula, ac varius nisl feugiat id. Sed magna felis, pharetra sed rutrum id, tempus sit amet tellus. In dapibus urna et sollicitudin consectetur. Fusce efficitur fermentum hendrerit.`
